<?php

/**
 * @file
 * Contains message_archiver.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function message_archiver_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the message_archiver module.
    case 'help.page.message_archiver':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Archives message texts') . '</p>';
      return $output;

    default:
  }
}
